name: 'sfd'

on: push
  


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Salesforce CLI
        run: |
          export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
          ./sfdx/install
          export PATH=./sfdx/$(pwd):$PATH
          sfdx --version
      - name: Auth with the DevHub
        run: 'sfdx auth:jwt:grant --clientid 3MVG9n_HvETGhr3DgwETpqNkWSmySzmQqr2iEEAJ.MKU5VzGKDKb5WorK2MLJ7wU66BjPAZXi4nAeyIcgckIF  --jwtkeyfile assets/server.key --username sanyamcmentor@gmail.com  --setdefaultdevhubusername --setalias my-hub-org'
      - name: Retrive from org
        run: 'sfdx force:source:retrieve -x manifest/package.xml -u sanyamcmentor@gmail.com'
      - name: git add
        run: git add .
      - name: Commit files
        run: |
            git config --local user.email "sanyam.jain.7376@gmail.com"
            git config --local user.name "sanyamjain7376"
            git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}
      
       
 
        
